version: '2.2'

services:
  react:
    container_name: armyreact
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.160.48:5000/esp21/react
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
